# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'TradersView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TradersView

pod 'SDWebImage', '~> 5.0'
pod 'GoogleSignIn'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

pod 'Alamofire', '~> 5.4'
pod 'SkyFloatingLabelTextField', '~> 3.0'

pod 'Firebase/Database'

end
